# Generated by Django 5.1.2 on 2024-10-22 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('accountType', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account')], max_length=16)),
                ('accountnumber', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Moneymanagement',
            fields=[
                ('bankmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankapp.bankmodel')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'moneymanagement',
                'ordering': ['-updated_at'],
            },
            bases=('bankapp.bankmodel',),
        ),
    ]
